import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header1 from "./components/header1";
import Header2 from "./components/header2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Asmita's Kitchen",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <Header1></Header1>
        <Header2></Header2>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
